# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-trainee-problem-avito' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-trainee-problem-avito
	pod 'PinLayout'

  target 'ios-trainee-problem-avitoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-trainee-problem-avitoUITests' do
    # Pods for testing
  end

end
